server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        try_files /client$uri /client$uri/ /client/index.html;
    }

    location /images/ {
        alias /usr/share/nginx/html/images/;
    }
}